name: CI Build

# Triggers the workflow on push or pull request events but only for the master branch
on:
  push:
    branches: [master]
  pull_request:
    branches: ["**"]

# This workflow contains a single job called "build_test"
jobs:
  build_test:
    name: Build & Test
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      # Checks-out the repository under $GITHUB_WORKSPACE, so the job can access it
      - name: Checkout
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 14
          registry-url: "https://npm.pkg.github.com"

      - name: Cache node_modules
        id: cache-task-ref
        env:
          cache-name: cache-node-modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('package.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install Dependencies
        if: steps.cache-task-ref.outputs.cache-hit != 'true'
        run: yarn install

      - name: Build Project
        run: yarn build

      - name: Unit Tests
        run: yarn test:unit
